os: linux
arch: ppc64le
dist: xenial
language: go
go:
    - "1.11"
addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
    packages:
      - squashfs
    update: true
services:
  - docker
python:
  - "3.6"
install:
#  - sudo apt-get install software-properties-common python-software-properties -y
#  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
#  - sudo apt-get update
#  - sudo apt-get install python3.6 -y
  - sudo apt-get install wget -y
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-ppc64le.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n travis python=$TRAVIS_PYTHON_VERSION
  - conda install -c anaconda opencv
  - conda activate travis
#  - python setup.py install
#  - sudo apt-get install python-opencv -y
  - which python
#  - which pip
  - which pip3
  - pip3 install -r requirements.txt
before_install:
  - chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh
script:
#  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
#  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - /bin/bash .travis/health_check.sh
  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6 || true
  - /bin/bash .travis/health_check.sh
  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6 || true
  - /bin/bash .travis/health_check.sh
  - python3 manage.py build
  - /bin/bash .travis/health_check.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
  - docker push sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - /bin/bash .travis/health_check.sh
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/test:/output --privileged -t --rm singularityware/docker2singularity sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
  - /bin/bash .travis/health_check.sh
  - singularity push --allow-unsigned `ls -1 /tmp/test/*.simg | head -1` library://sampyash/default/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
  - /bin/bash .travis/health_check.sh
  - sudo rm `ls -1 /tmp/test/*.simg | head -1`
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/test:/output --privileged -t --rm singularityware/docker2singularity sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - /bin/bash .travis/health_check.sh
  - singularity push --allow-unsigned `ls -1 /tmp/test/*.simg | head -1` library://sampyash/default/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - /bin/bash .travis/health_check.sh
