dist: bionic
language: go
go:
    - "1.11"
addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
    packages:
      - squashfs
    update: true
services:
  - docker
python:
  - "3.6"
install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6
  - sudo apt-get update
  - sudo apt-get install python3.6
  - pip install -r requirements.txt
before_install:
  - chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh
script:
#  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
#  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6 || true
  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6 || true
  - python manage.py build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
  - docker push sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/test:/output --privileged -t --rm singularityware/docker2singularity sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
  - singularity push --allow-unsigned `ls -1 /tmp/test/*.simg | head -1` library://sampyash/default/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
  - sudo rm `ls -1 /tmp/test/*.simg | head -1`
  - docker run -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/test:/output --privileged -t --rm singularityware/docker2singularity sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - singularity push --allow-unsigned `ls -1 /tmp/test/*.simg | head -1` library://sampyash/default/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
