dist: bionic
language: go
go:
    - "1.11"
addons:
  apt:
    packages:
      - flawfinder
      - squashfs-tools
      - uuid-dev
      - libuuid1
      - libffi-dev
      - libssl-dev
      - libssl1.0.0
      - libarchive-dev
      - libgpgme11-dev
      - libseccomp-dev
  homebrew:
    packages:
      - squashfs
    update: true
services:
  - docker
python:
  - "3.6"
install:
#  - sudo apt-get install software-properties-common python-software-properties -y
#  - sudo add-apt-repository ppa:jonathonf/python-3.6 -y
#  - sudo apt-get update
#  - sudo apt-get install python3.6 -y
#  - pip3 install -r requirements.txt
  - pip3 install --upgrade pip3
  - pip3 install click
  - pip3 install imgaug
before_install:
  - chmod u+x .travis/*.sh
  - /bin/bash .travis/setup.sh
script:
#  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_cpu_0.0.6
#  - docker pull sampyash/vt_cs_6604_digital_libraries:deepfigures_gpu_0.0.6
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - /bin/bash .travis/health_check.sh
  - python manage.py build-full dockerfiles/cpu/build_config.json
  - /bin/bash .travis/health_check.sh
  - docker system prune --all --force
  - /bin/bash .travis/health_check.sh
  - python3 manage.py build-full dockerfiles/gpu/build_config.json
  - /bin/bash .travis/health_check.sh