# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: deepfigures-open

on:
  push:
    branches:
      - master
      - adding_some_documentation 
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda Python 3.6
      uses: s-weigand/setup-conda@v1
      with:
        python-version: 3.6
        activate-conda: true
        conda-channels: anaconda, conda-forge
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt --no-cache-dir; fi
        python setup.py install
        cd vendor/tensorboxresnet && python setup.py install && cd ../..
    - name: Check tensorboxresnet
      run: python -c "import tensorboxresnet; print(tensorboxresnet.__path__)"

